# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: Alsvin-5GAPI
    build: .
    command: gunicorn -b 0.0.0.0:5000 Alsvin-5GAPI.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/Alsvin-5GAPI.db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./Alsvin-5GAPI:/code/Alsvin-5GAPI
      - ./db/:/db/
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: Alsvin-5GAPI
    command: "celery worker -A Alsvin-5GAPI.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
