# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: alsvin-5g-api
    build: .
    command: gunicorn -b 0.0.0.0:5000 alsvin-5g-api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/alsvin-5g-api.db
    volumes:
      - ./alsvin-5g-api:/code/alsvin-5g-api
      - ./db/:/db/
    ports:
      - "5000:5000"
